<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'iso3' => 'AFG', 'flag' => '🇦🇫', 'currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani', 'currency_symbol' => '؋', 'phone_code' => '+93'],
            ['name' => 'Albania', 'code' => 'AL', 'iso3' => 'ALB', 'flag' => '🇦🇱', 'currency_code' => 'ALL', 'currency_name' => 'Albanian Lek', 'currency_symbol' => 'L', 'phone_code' => '+355'],
            ['name' => 'Algeria', 'code' => 'DZ', 'iso3' => 'DZA', 'flag' => '🇩🇿', 'currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar', 'currency_symbol' => 'د.ج', 'phone_code' => '+213'],
            ['name' => 'American Samoa', 'code' => 'AS', 'iso3' => 'ASM', 'flag' => '🇦🇸', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1684'],
            ['name' => 'Andorra', 'code' => 'AD', 'iso3' => 'AND', 'flag' => '🇦🇩', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+376'],
            ['name' => 'Angola', 'code' => 'AO', 'iso3' => 'AGO', 'flag' => '🇦🇴', 'currency_code' => 'AOA', 'currency_name' => 'Angolan Kwanza', 'currency_symbol' => 'Kz', 'phone_code' => '+244'],
            ['name' => 'Anguilla', 'code' => 'AI', 'iso3' => 'AIA', 'flag' => '🇦🇮', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1264'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'iso3' => 'ATA', 'flag' => '🇦🇶', 'currency_code' => null, 'currency_name' => null, 'currency_symbol' => null, 'phone_code' => '+672'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'iso3' => 'ATG', 'flag' => '🇦🇬', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1268'],
            ['name' => 'Argentina', 'code' => 'AR', 'iso3' => 'ARG', 'flag' => '🇦🇷', 'currency_code' => 'ARS', 'currency_name' => 'Argentine Peso', 'currency_symbol' => '$', 'phone_code' => '+54'],
            ['name' => 'Armenia', 'code' => 'AM', 'iso3' => 'ARM', 'flag' => '🇦🇲', 'currency_code' => 'AMD', 'currency_name' => 'Armenian Dram', 'currency_symbol' => '֏', 'phone_code' => '+374'],
            ['name' => 'Aruba', 'code' => 'AW', 'iso3' => 'ABW', 'flag' => '🇦🇼', 'currency_code' => 'AWG', 'currency_name' => 'Aruban Florin', 'currency_symbol' => 'ƒ', 'phone_code' => '+297'],
            ['name' => 'Australia', 'code' => 'AU', 'iso3' => 'AUS', 'flag' => '🇦🇺', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => '+61'],
            ['name' => 'Austria', 'code' => 'AT', 'iso3' => 'AUT', 'flag' => '🇦🇹', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+43'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'iso3' => 'AZE', 'flag' => '🇦🇿', 'currency_code' => 'AZN', 'currency_name' => 'Azerbaijani Manat', 'currency_symbol' => '₼', 'phone_code' => '+994'],
            ['name' => 'Bahamas', 'code' => 'BS', 'iso3' => 'BHS', 'flag' => '🇧🇸', 'currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar', 'currency_symbol' => '$', 'phone_code' => '+1242'],
            ['name' => 'Bahrain', 'code' => 'BH', 'iso3' => 'BHR', 'flag' => '🇧🇭', 'currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar', 'currency_symbol' => '.د.ب', 'phone_code' => '+973'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'iso3' => 'BGD', 'flag' => '🇧🇩', 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka', 'currency_symbol' => '৳', 'phone_code' => '+880'],
            ['name' => 'Barbados', 'code' => 'BB', 'iso3' => 'BRB', 'flag' => '🇧🇧', 'currency_code' => 'BBD', 'currency_name' => 'Barbadian Dollar', 'currency_symbol' => '$', 'phone_code' => '+1246'],
            ['name' => 'Belarus', 'code' => 'BY', 'iso3' => 'BLR', 'flag' => '🇧🇾', 'currency_code' => 'BYN', 'currency_name' => 'Belarusian Ruble', 'currency_symbol' => 'Br', 'phone_code' => '+375'],
            ['name' => 'Belgium', 'code' => 'BE', 'iso3' => 'BEL', 'flag' => '🇧🇪', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+32'],
            ['name' => 'Belize', 'code' => 'BZ', 'iso3' => 'BLZ', 'flag' => '🇧🇿', 'currency_code' => 'BZD', 'currency_name' => 'Belize Dollar', 'currency_symbol' => '$', 'phone_code' => '+501'],
            ['name' => 'Benin', 'code' => 'BJ', 'iso3' => 'BEN', 'flag' => '🇧🇯', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+229'],
            ['name' => 'Bermuda', 'code' => 'BM', 'iso3' => 'BMU', 'flag' => '🇧🇲', 'currency_code' => 'BMD', 'currency_name' => 'Bermudian Dollar', 'currency_symbol' => '$', 'phone_code' => '+1441'],
            ['name' => 'Bhutan', 'code' => 'BT', 'iso3' => 'BTN', 'flag' => '🇧🇹', 'currency_code' => 'BTN', 'currency_name' => 'Bhutanese Ngultrum', 'currency_symbol' => 'Nu.', 'phone_code' => '+975'],
            ['name' => 'Bolivia', 'code' => 'BO', 'iso3' => 'BOL', 'flag' => '🇧🇴', 'currency_code' => 'BOB', 'currency_name' => 'Bolivian Boliviano', 'currency_symbol' => 'Bs.', 'phone_code' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'iso3' => 'BIH', 'flag' => '🇧🇦', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia-Herzegovina Convertible Mark', 'currency_symbol' => 'КМ', 'phone_code' => '+387'],
            ['name' => 'Botswana', 'code' => 'BW', 'iso3' => 'BWA', 'flag' => '🇧🇼', 'currency_code' => 'BWP', 'currency_name' => 'Botswanan Pula', 'currency_symbol' => 'P', 'phone_code' => '+267'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'iso3' => 'BVT', 'flag' => '🇧🇻', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'currency_symbol' => 'kr', 'phone_code' => '+47'],
            ['name' => 'Brazil', 'code' => 'BR', 'iso3' => 'BRA', 'flag' => '🇧🇷', 'currency_code' => 'BRL', 'currency_name' => 'Brazilian Real', 'currency_symbol' => 'R$', 'phone_code' => '+55'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'iso3' => 'IOT', 'flag' => '🇮🇴', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+246'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'iso3' => 'BRN', 'flag' => '🇧🇳', 'currency_code' => 'BND', 'currency_name' => 'Brunei Dollar', 'currency_symbol' => '$', 'phone_code' => '+673'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'iso3' => 'BGR', 'flag' => '🇧🇬', 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev', 'currency_symbol' => 'лв', 'phone_code' => '+359'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'iso3' => 'BFA', 'flag' => '🇧🇫', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+226'],
            ['name' => 'Burundi', 'code' => 'BI', 'iso3' => 'BDI', 'flag' => '🇧🇮', 'currency_code' => 'BIF', 'currency_name' => 'Burundian Franc', 'currency_symbol' => 'FBu', 'phone_code' => '+257'],
            ['name' => 'Cambodia', 'code' => 'KH', 'iso3' => 'KHM', 'flag' => '🇰🇭', 'currency_code' => 'KHR', 'currency_name' => 'Cambodian Riel', 'currency_symbol' => '៛', 'phone_code' => '+855'],
            ['name' => 'Cameroon', 'code' => 'CM', 'iso3' => 'CMR', 'flag' => '🇨🇲', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_symbol' => 'FCFA', 'phone_code' => '+237'],
            ['name' => 'Canada', 'code' => 'CA', 'iso3' => 'CAN', 'flag' => '🇨🇦', 'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar', 'currency_symbol' => '$', 'phone_code' => '+1'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'iso3' => 'CPV', 'flag' => '🇨🇻', 'currency_code' => 'CVE', 'currency_name' => 'Cape Verdean Escudo', 'currency_symbol' => '$', 'phone_code' => '+238'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'iso3' => 'CYM', 'flag' => '🇰🇾', 'currency_code' => 'KYD', 'currency_name' => 'Cayman Islands Dollar', 'currency_symbol' => '$', 'phone_code' => '+1345'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'iso3' => 'CAF', 'flag' => '🇨🇫', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_symbol' => 'FCFA', 'phone_code' => '+236'],
            ['name' => 'Chad', 'code' => 'TD', 'iso3' => 'TCD', 'flag' => '🇹🇩', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_symbol' => 'FCFA', 'phone_code' => '+235'],
            ['name' => 'Chile', 'code' => 'CL', 'iso3' => 'CHL', 'flag' => '🇨🇱', 'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso', 'currency_symbol' => '$', 'phone_code' => '+56'],
            ['name' => 'China', 'code' => 'CN', 'iso3' => 'CHN', 'flag' => '🇨🇳', 'currency_code' => 'CNY', 'currency_name' => 'Chinese Yuan', 'currency_symbol' => '¥', 'phone_code' => '+86'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'iso3' => 'CXR', 'flag' => '🇨🇽', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => '+61'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'iso3' => 'CCK', 'flag' => '🇨🇨', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => '+61'],
            ['name' => 'Colombia', 'code' => 'CO', 'iso3' => 'COL', 'flag' => '🇨🇴', 'currency_code' => 'COP', 'currency_name' => 'Colombian Peso', 'currency_symbol' => '$', 'phone_code' => '+57'],
            ['name' => 'Comoros', 'code' => 'KM', 'iso3' => 'COM', 'flag' => '🇰🇲', 'currency_code' => 'KMF', 'currency_name' => 'Comorian Franc', 'currency_symbol' => 'CF', 'phone_code' => '+269'],
            ['name' => 'Congo', 'code' => 'CG', 'iso3' => 'COG', 'flag' => '🇨🇬', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_symbol' => 'FCFA', 'phone_code' => '+242'],
            ['name' => 'Congo, Democratic Republic', 'code' => 'CD', 'iso3' => 'COD', 'flag' => '🇨🇩', 'currency_code' => 'CDF', 'currency_name' => 'Congolese Franc', 'currency_symbol' => 'FC', 'phone_code' => '+243'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'iso3' => 'COK', 'flag' => '🇨🇰', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$', 'phone_code' => '+682'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'iso3' => 'CRI', 'flag' => '🇨🇷', 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colón', 'currency_symbol' => '₡', 'phone_code' => '+506'],
            ['name' => 'Cote D\'Ivoire', 'code' => 'CI', 'iso3' => 'CIV', 'flag' => '🇨🇮', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+225'],
            ['name' => 'Croatia', 'code' => 'HR', 'iso3' => 'HRV', 'flag' => '🇭🇷', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+385'],
            ['name' => 'Cuba', 'code' => 'CU', 'iso3' => 'CUB', 'flag' => '🇨🇺', 'currency_code' => 'CUP', 'currency_name' => 'Cuban Peso', 'currency_symbol' => '$', 'phone_code' => '+53'],
            ['name' => 'Cyprus', 'code' => 'CY', 'iso3' => 'CYP', 'flag' => '🇨🇾', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+357'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'iso3' => 'CZE', 'flag' => '🇨🇿', 'currency_code' => 'CZK', 'currency_name' => 'Czech Republic Koruna', 'currency_symbol' => 'Kč', 'phone_code' => '+420'],
            ['name' => 'Denmark', 'code' => 'DK', 'iso3' => 'DNK', 'flag' => '🇩🇰', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'currency_symbol' => 'kr', 'phone_code' => '+45'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'iso3' => 'DJI', 'flag' => '🇩🇯', 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian Franc', 'currency_symbol' => 'Fdj', 'phone_code' => '+253'],
            ['name' => 'Dominica', 'code' => 'DM', 'iso3' => 'DMA', 'flag' => '🇩🇲', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1767'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'iso3' => 'DOM', 'flag' => '🇩🇴', 'currency_code' => 'DOP', 'currency_name' => 'Dominican Peso', 'currency_symbol' => 'RD$', 'phone_code' => '+1809'],
            ['name' => 'Ecuador', 'code' => 'EC', 'iso3' => 'ECU', 'flag' => '🇪🇨', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+593'],
            ['name' => 'Egypt', 'code' => 'EG', 'iso3' => 'EGY', 'flag' => '🇪🇬', 'currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound', 'currency_symbol' => '£', 'phone_code' => '+20'],
            ['name' => 'El Salvador', 'code' => 'SV', 'iso3' => 'SLV', 'flag' => '🇸🇻', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+503'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'iso3' => 'GNQ', 'flag' => '🇬🇶', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_symbol' => 'FCFA', 'phone_code' => '+240'],
            ['name' => 'Eritrea', 'code' => 'ER', 'iso3' => 'ERI', 'flag' => '🇪🇷', 'currency_code' => 'ERN', 'currency_name' => 'Eritrean Nakfa', 'currency_symbol' => 'Nfk', 'phone_code' => '+291'],
            ['name' => 'Estonia', 'code' => 'EE', 'iso3' => 'EST', 'flag' => '🇪🇪', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+372'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'iso3' => 'ETH', 'flag' => '🇪🇹', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr', 'currency_symbol' => 'Br', 'phone_code' => '+251'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'iso3' => 'FLK', 'flag' => '🇫🇰', 'currency_code' => 'FKP', 'currency_name' => 'Falkland Islands Pound', 'currency_symbol' => '£', 'phone_code' => '+500'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'iso3' => 'FRO', 'flag' => '🇫🇴', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'currency_symbol' => 'kr', 'phone_code' => '+298'],
            ['name' => 'Fiji', 'code' => 'FJ', 'iso3' => 'FJI', 'flag' => '🇫🇯', 'currency_code' => 'FJD', 'currency_name' => 'Fijian Dollar', 'currency_symbol' => '$', 'phone_code' => '+679'],
            ['name' => 'Finland', 'code' => 'FI', 'iso3' => 'FIN', 'flag' => '🇫🇮', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+358'],
            ['name' => 'France', 'code' => 'FR', 'iso3' => 'FRA', 'flag' => '🇫🇷', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+33'],
            ['name' => 'French Guiana', 'code' => 'GF', 'iso3' => 'GUF', 'flag' => '🇬🇫', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+594'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'iso3' => 'PYF', 'flag' => '🇵🇫', 'currency_code' => 'XPF', 'currency_name' => 'CFP Franc', 'currency_symbol' => '₣', 'phone_code' => '+689'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'iso3' => 'ATF', 'flag' => '🇹🇫', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+262'],
            ['name' => 'Gabon', 'code' => 'GA', 'iso3' => 'GAB', 'flag' => '🇬🇦', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_symbol' => 'FCFA', 'phone_code' => '+241'],
            ['name' => 'Gambia', 'code' => 'GM', 'iso3' => 'GMB', 'flag' => '🇬🇲', 'currency_code' => 'GMD', 'currency_name' => 'Gambian Dalasi', 'currency_symbol' => 'D', 'phone_code' => '+220'],
            ['name' => 'Georgia', 'code' => 'GE', 'iso3' => 'GEO', 'flag' => '🇬🇪', 'currency_code' => 'GEL', 'currency_name' => 'Georgian Lari', 'currency_symbol' => '₾', 'phone_code' => '+995'],
            ['name' => 'Germany', 'code' => 'DE', 'iso3' => 'DEU', 'flag' => '🇩🇪', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+49'],
            ['name' => 'Ghana', 'code' => 'GH', 'iso3' => 'GHA', 'flag' => '🇬🇭', 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi', 'currency_symbol' => '₵', 'phone_code' => '+233'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'iso3' => 'GIB', 'flag' => '🇬🇮', 'currency_code' => 'GIP', 'currency_name' => 'Gibraltar Pound', 'currency_symbol' => '£', 'phone_code' => '+350'],
            ['name' => 'Greece', 'code' => 'GR', 'iso3' => 'GRC', 'flag' => '🇬🇷', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+30'],
            ['name' => 'Greenland', 'code' => 'GL', 'iso3' => 'GRL', 'flag' => '🇬🇱', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'currency_symbol' => 'kr', 'phone_code' => '+299'],
            ['name' => 'Grenada', 'code' => 'GD', 'iso3' => 'GRD', 'flag' => '🇬🇩', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1473'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'iso3' => 'GLP', 'flag' => '🇬🇵', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+590'],
            ['name' => 'Guam', 'code' => 'GU', 'iso3' => 'GUM', 'flag' => '🇬🇺', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1671'],
            ['name' => 'Guatemala', 'code' => 'GT', 'iso3' => 'GTM', 'flag' => '🇬🇹', 'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal', 'currency_symbol' => 'Q', 'phone_code' => '+502'],
            ['name' => 'Guernsey', 'code' => 'GG', 'iso3' => 'GGY', 'flag' => '🇬🇬', 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'currency_symbol' => '£', 'phone_code' => '+44'],
            ['name' => 'Guinea', 'code' => 'GN', 'iso3' => 'GIN', 'flag' => '🇬🇳', 'currency_code' => 'GNF', 'currency_name' => 'Guinean Franc', 'currency_symbol' => 'FG', 'phone_code' => '+224'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'iso3' => 'GNB', 'flag' => '🇬🇼', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+245'],
            ['name' => 'Guyana', 'code' => 'GY', 'iso3' => 'GUY', 'flag' => '🇬🇾', 'currency_code' => 'GYD', 'currency_name' => 'Guyanaese Dollar', 'currency_symbol' => '$', 'phone_code' => '+592'],
            ['name' => 'Haiti', 'code' => 'HT', 'iso3' => 'HTI', 'flag' => '🇭🇹', 'currency_code' => 'HTG', 'currency_name' => 'Haitian Gourde', 'currency_symbol' => 'G', 'phone_code' => '+509'],
            ['name' => 'Heard Island & Mcdonald Islands', 'code' => 'HM', 'iso3' => 'HMD', 'flag' => '🇭🇲', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => null],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'iso3' => 'VAT', 'flag' => '🇻🇦', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+379'],
            ['name' => 'Honduras', 'code' => 'HN', 'iso3' => 'HND', 'flag' => '🇭🇳', 'currency_code' => 'HNL', 'currency_name' => 'Honduran Lempira', 'currency_symbol' => 'L', 'phone_code' => '+504'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'iso3' => 'HKG', 'flag' => '🇭🇰', 'currency_code' => 'HKD', 'currency_name' => 'Hong Kong Dollar', 'currency_symbol' => '$', 'phone_code' => '+852'],
            ['name' => 'Hungary', 'code' => 'HU', 'iso3' => 'HUN', 'flag' => '🇭🇺', 'currency_code' => 'HUF', 'currency_name' => 'Hungarian Forint', 'currency_symbol' => 'Ft', 'phone_code' => '+36'],
            ['name' => 'Iceland', 'code' => 'IS', 'iso3' => 'ISL', 'flag' => '🇮🇸', 'currency_code' => 'ISK', 'currency_name' => 'Icelandic Króna', 'currency_symbol' => 'kr', 'phone_code' => '+354'],
            ['name' => 'India', 'code' => 'IN', 'iso3' => 'IND', 'flag' => '🇮🇳', 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'currency_symbol' => '₹', 'phone_code' => '+91'],
            ['name' => 'Indonesia', 'code' => 'ID', 'iso3' => 'IDN', 'flag' => '🇮🇩', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah', 'currency_symbol' => 'Rp', 'phone_code' => '+62'],
            ['name' => 'Iran, Islamic Republic Of', 'code' => 'IR', 'iso3' => 'IRN', 'flag' => '🇮🇷', 'currency_code' => 'IRR', 'currency_name' => 'Iranian Rial', 'currency_symbol' => '﷼', 'phone_code' => '+98'],
            ['name' => 'Iraq', 'code' => 'IQ', 'iso3' => 'IRQ', 'flag' => '🇮🇶', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar', 'currency_symbol' => 'ع.د', 'phone_code' => '+964'],
            ['name' => 'Ireland', 'code' => 'IE', 'iso3' => 'IRL', 'flag' => '🇮🇪', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+353'],
            ['name' => 'Isle Of Man', 'code' => 'IM', 'iso3' => 'IMN', 'flag' => '🇮🇲', 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'currency_symbol' => '£', 'phone_code' => '+44'],
            ['name' => 'Israel', 'code' => 'IL', 'iso3' => 'ISR', 'flag' => '🇮🇱', 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Sheqel', 'currency_symbol' => '₪', 'phone_code' => '+972'],
            ['name' => 'Italy', 'code' => 'IT', 'iso3' => 'ITA', 'flag' => '🇮🇹', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+39'],
            ['name' => 'Jamaica', 'code' => 'JM', 'iso3' => 'JAM', 'flag' => '🇯🇲', 'currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar', 'currency_symbol' => '$', 'phone_code' => '+1876'],
            ['name' => 'Japan', 'code' => 'JP', 'iso3' => 'JPN', 'flag' => '🇯🇵', 'currency_code' => 'JPY', 'currency_name' => 'Japanese Yen', 'currency_symbol' => '¥', 'phone_code' => '+81'],
            ['name' => 'Jersey', 'code' => 'JE', 'iso3' => 'JEY', 'flag' => '🇯🇪', 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'currency_symbol' => '£', 'phone_code' => '+44'],
            ['name' => 'Jordan', 'code' => 'JO', 'iso3' => 'JOR', 'flag' => '🇯🇴', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar', 'currency_symbol' => 'JD', 'phone_code' => '+962'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'iso3' => 'KAZ', 'flag' => '🇰🇿', 'currency_code' => 'KZT', 'currency_name' => 'Kazakhstani Tenge', 'currency_symbol' => '₸', 'phone_code' => '+7'],
            ['name' => 'Kenya', 'code' => 'KE', 'iso3' => 'KEN', 'flag' => '🇰🇪', 'currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling', 'currency_symbol' => 'KSh', 'phone_code' => '+254'],
            ['name' => 'Kiribati', 'code' => 'KI', 'iso3' => 'KIR', 'flag' => '🇰🇮', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => '+686'],
            ['name' => 'Korea', 'code' => 'KR', 'iso3' => 'KOR', 'flag' => '🇰🇷', 'currency_code' => 'KRW', 'currency_name' => 'South Korean Won', 'currency_symbol' => '₩', 'phone_code' => '+82'],
            ['name' => 'Kuwait', 'code' => 'KW', 'iso3' => 'KWT', 'flag' => '🇰🇼', 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar', 'currency_symbol' => 'KD', 'phone_code' => '+965'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'iso3' => 'KGZ', 'flag' => '🇰🇬', 'currency_code' => 'KGS', 'currency_name' => 'Kyrgystani Som', 'currency_symbol' => 'с', 'phone_code' => '+996'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'iso3' => 'LAO', 'flag' => '🇱🇦', 'currency_code' => 'LAK', 'currency_name' => 'Laotian Kip', 'currency_symbol' => '₭', 'phone_code' => '+856'],
            ['name' => 'Latvia', 'code' => 'LV', 'iso3' => 'LVA', 'flag' => '🇱🇻', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+371'],
            ['name' => 'Lebanon', 'code' => 'LB', 'iso3' => 'LBN', 'flag' => '🇱🇧', 'currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound', 'currency_symbol' => 'L£', 'phone_code' => '+961'],
            ['name' => 'Lesotho', 'code' => 'LS', 'iso3' => 'LSO', 'flag' => '🇱🇸', 'currency_code' => 'LSL', 'currency_name' => 'Lesotho Loti', 'currency_symbol' => 'M', 'phone_code' => '+266'],
            ['name' => 'Liberia', 'code' => 'LR', 'iso3' => 'LBR', 'flag' => '🇱🇷', 'currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar', 'currency_symbol' => '$', 'phone_code' => '+231'],
            ['name' => 'Libyan Arab Jamahiriya', 'code' => 'LY', 'iso3' => 'LBY', 'flag' => '🇱🇾', 'currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar', 'currency_symbol' => 'LD', 'phone_code' => '+218'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'iso3' => 'LIE', 'flag' => '🇱🇮', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'currency_symbol' => 'Fr', 'phone_code' => '+423'],
            ['name' => 'Lithuania', 'code' => 'LT', 'iso3' => 'LTU', 'flag' => '🇱🇹', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+370'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'iso3' => 'LUX', 'flag' => '🇱🇺', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+352'],
            ['name' => 'Macao', 'code' => 'MO', 'iso3' => 'MAC', 'flag' => '🇲🇴', 'currency_code' => 'MOP', 'currency_name' => 'Macanese Pataca', 'currency_symbol' => 'MOP$', 'phone_code' => '+853'],
            ['name' => 'Macedonia', 'code' => 'MK', 'iso3' => 'MKD', 'flag' => '🇲🇰', 'currency_code' => 'MKD', 'currency_name' => 'Macedonian Denar', 'currency_symbol' => 'ден', 'phone_code' => '+389'],
            ['name' => 'Madagascar', 'code' => 'MG', 'iso3' => 'MDG', 'flag' => '🇲🇬', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy Ariary', 'currency_symbol' => 'Ar', 'phone_code' => '+261'],
            ['name' => 'Malawi', 'code' => 'MW', 'iso3' => 'MWI', 'flag' => '🇲🇼', 'currency_code' => 'MWK', 'currency_name' => 'Malawian Kwacha', 'currency_symbol' => 'MK', 'phone_code' => '+265'],
            ['name' => 'Malaysia', 'code' => 'MY', 'iso3' => 'MYS', 'flag' => '🇲🇾', 'currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit', 'currency_symbol' => 'RM', 'phone_code' => '+60'],
            ['name' => 'Maldives', 'code' => 'MV', 'iso3' => 'MDV', 'flag' => '🇲🇻', 'currency_code' => 'MVR', 'currency_name' => 'Maldivian Rufiyaa', 'currency_symbol' => 'Rf', 'phone_code' => '+960'],
            ['name' => 'Mali', 'code' => 'ML', 'iso3' => 'MLI', 'flag' => '🇲🇱', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+223'],
            ['name' => 'Malta', 'code' => 'MT', 'iso3' => 'MLT', 'flag' => '🇲🇹', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+356'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'iso3' => 'MHL', 'flag' => '🇲🇭', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+692'],
            ['name' => 'Martinique', 'code' => 'MQ', 'iso3' => 'MTQ', 'flag' => '🇲🇶', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+596'],
            ['name' => 'Mauritania', 'code' => 'MR', 'iso3' => 'MRT', 'flag' => '🇲🇷', 'currency_code' => 'MRO', 'currency_name' => 'Mauritanian Ouguiya', 'currency_symbol' => 'UM', 'phone_code' => '+222'],
            ['name' => 'Mauritius', 'code' => 'MU', 'iso3' => 'MUS', 'flag' => '🇲🇺', 'currency_code' => 'MUR', 'currency_name' => 'Mauritian Rupee', 'currency_symbol' => '₨', 'phone_code' => '+230'],
            ['name' => 'Mayotte', 'code' => 'YT', 'iso3' => 'MYT', 'flag' => '🇾🇹', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+262'],
            ['name' => 'Mexico', 'code' => 'MX', 'iso3' => 'MEX', 'flag' => '🇲🇽', 'currency_code' => 'MXN', 'currency_name' => 'Mexican Peso', 'currency_symbol' => '$', 'phone_code' => '+52'],
            ['name' => 'Micronesia, Federated States Of', 'code' => 'FM', 'iso3' => 'FSM', 'flag' => '🇫🇲', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+691'],
            ['name' => 'Moldova', 'code' => 'MD', 'iso3' => 'MDA', 'flag' => '🇲🇩', 'currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu', 'currency_symbol' => 'L', 'phone_code' => '+373'],
            ['name' => 'Monaco', 'code' => 'MC', 'iso3' => 'MCO', 'flag' => '🇲🇨', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+377'],
            ['name' => 'Mongolia', 'code' => 'MN', 'iso3' => 'MNG', 'flag' => '🇲🇳', 'currency_code' => 'MNT', 'currency_name' => 'Mongolian Tugrik', 'currency_symbol' => '₮', 'phone_code' => '+976'],
            ['name' => 'Montenegro', 'code' => 'ME', 'iso3' => 'MNE', 'flag' => '🇲🇪', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+382'],
            ['name' => 'Montserrat', 'code' => 'MS', 'iso3' => 'MSR', 'flag' => '🇲🇸', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1664'],
            ['name' => 'Morocco', 'code' => 'MA', 'iso3' => 'MAR', 'flag' => '🇲🇦', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham', 'currency_symbol' => 'DH', 'phone_code' => '+212'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'iso3' => 'MOZ', 'flag' => '🇲🇿', 'currency_code' => 'MZN', 'currency_name' => 'Mozambican Metical', 'currency_symbol' => 'MT', 'phone_code' => '+258'],
            ['name' => 'Myanmar', 'code' => 'MM', 'iso3' => 'MMR', 'flag' => '🇲🇲', 'currency_code' => 'MMK', 'currency_name' => 'Myanmar Kyat', 'currency_symbol' => 'K', 'phone_code' => '+95'],
            ['name' => 'Namibia', 'code' => 'NA', 'iso3' => 'NAM', 'flag' => '🇳🇦', 'currency_code' => 'NAD', 'currency_name' => 'Namibian Dollar', 'currency_symbol' => '$', 'phone_code' => '+264'],
            ['name' => 'Nauru', 'code' => 'NR', 'iso3' => 'NRU', 'flag' => '🇳🇷', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => '+674'],
            ['name' => 'Nepal', 'code' => 'NP', 'iso3' => 'NPL', 'flag' => '🇳🇵', 'currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee', 'currency_symbol' => '₨', 'phone_code' => '+977'],
            ['name' => 'Netherlands', 'code' => 'NL', 'iso3' => 'NLD', 'flag' => '🇳🇱', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+31'],
            ['name' => 'Netherlands Antilles', 'code' => 'AN', 'iso3' => 'ANT', 'flag' => null, 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antillean Guilder', 'currency_symbol' => 'ƒ', 'phone_code' => '+599'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'iso3' => 'NCL', 'flag' => '🇳🇨', 'currency_code' => 'XPF', 'currency_name' => 'CFP Franc', 'currency_symbol' => '₣', 'phone_code' => '+687'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'iso3' => 'NZL', 'flag' => '🇳🇿', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$', 'phone_code' => '+64'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'iso3' => 'NIC', 'flag' => '🇳🇮', 'currency_code' => 'NIO', 'currency_name' => 'Nicaraguan Córdoba', 'currency_symbol' => 'C$', 'phone_code' => '+505'],
            ['name' => 'Niger', 'code' => 'NE', 'iso3' => 'NER', 'flag' => '🇳🇪', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+227'],
            ['name' => 'Nigeria', 'code' => 'NG', 'iso3' => 'NGA', 'flag' => '🇳🇬', 'currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira', 'currency_symbol' => '₦', 'phone_code' => '+234'],
            ['name' => 'Niue', 'code' => 'NU', 'iso3' => 'NIU', 'flag' => '🇳🇺', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$', 'phone_code' => '+683'],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'iso3' => 'NFK', 'flag' => '🇳🇫', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => '+672'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'iso3' => 'MNP', 'flag' => '🇲🇵', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1670'],
            ['name' => 'Norway', 'code' => 'NO', 'iso3' => 'NOR', 'flag' => '🇳🇴', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'currency_symbol' => 'kr', 'phone_code' => '+47'],
            ['name' => 'Oman', 'code' => 'OM', 'iso3' => 'OMN', 'flag' => '🇴🇲', 'currency_code' => 'OMR', 'currency_name' => 'Omani Rial', 'currency_symbol' => '﷼', 'phone_code' => '+968'],
            ['name' => 'Pakistan', 'code' => 'PK', 'iso3' => 'PAK', 'flag' => '🇵🇰', 'currency_code' => 'PKR', 'currency_name' => 'Pakistani Rupee', 'currency_symbol' => '₨', 'phone_code' => '+92'],
            ['name' => 'Palau', 'code' => 'PW', 'iso3' => 'PLW', 'flag' => '🇵🇼', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+680'],
            ['name' => 'Palestinian Territory, Occupied', 'code' => 'PS', 'iso3' => 'PSE', 'flag' => '🇵🇸', 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Sheqel', 'currency_symbol' => '₪', 'phone_code' => '+970'],
            ['name' => 'Panama', 'code' => 'PA', 'iso3' => 'PAN', 'flag' => '🇵🇦', 'currency_code' => 'PAB', 'currency_name' => 'Panamanian Balboa', 'currency_symbol' => 'B/.', 'phone_code' => '+507'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'iso3' => 'PNG', 'flag' => '🇵🇬', 'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean Kina', 'currency_symbol' => 'K', 'phone_code' => '+675'],
            ['name' => 'Paraguay', 'code' => 'PY', 'iso3' => 'PRY', 'flag' => '🇵🇾', 'currency_code' => 'PYG', 'currency_name' => 'Paraguayan Guarani', 'currency_symbol' => 'Gs', 'phone_code' => '+595'],
            ['name' => 'Peru', 'code' => 'PE', 'iso3' => 'PER', 'flag' => '🇵🇪', 'currency_code' => 'PEN', 'currency_name' => 'Peruvian Nuevo Sol', 'currency_symbol' => 'S/.', 'phone_code' => '+51'],
            ['name' => 'Philippines', 'code' => 'PH', 'iso3' => 'PHL', 'flag' => '🇵🇭', 'currency_code' => 'PHP', 'currency_name' => 'Philippine Peso', 'currency_symbol' => '₱', 'phone_code' => '+63'],
            ['name' => 'Pitcairn', 'code' => 'PN', 'iso3' => 'PCN', 'flag' => '🇵🇳', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$', 'phone_code' => '+64'],
            ['name' => 'Poland', 'code' => 'PL', 'iso3' => 'POL', 'flag' => '🇵🇱', 'currency_code' => 'PLN', 'currency_name' => 'Polish Zloty', 'currency_symbol' => 'zł', 'phone_code' => '+48'],
            ['name' => 'Portugal', 'code' => 'PT', 'iso3' => 'PRT', 'flag' => '🇵🇹', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+351'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'iso3' => 'PRI', 'flag' => '🇵🇷', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1787'],
            ['name' => 'Qatar', 'code' => 'QA', 'iso3' => 'QAT', 'flag' => '🇶🇦', 'currency_code' => 'QAR', 'currency_name' => 'Qatari Rial', 'currency_symbol' => '﷼', 'phone_code' => '+974'],
            ['name' => 'Reunion', 'code' => 'RE', 'iso3' => 'REU', 'flag' => '🇷🇪', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+262'],
            ['name' => 'Romania', 'code' => 'RO', 'iso3' => 'ROU', 'flag' => '🇷🇴', 'currency_code' => 'RON', 'currency_name' => 'Romanian Leu', 'currency_symbol' => 'lei', 'phone_code' => '+40'],
            ['name' => 'Russian Federation', 'code' => 'RU', 'iso3' => 'RUS', 'flag' => '🇷🇺', 'currency_code' => 'RUB', 'currency_name' => 'Russian Ruble', 'currency_symbol' => '₽', 'phone_code' => '+7'],
            ['name' => 'Rwanda', 'code' => 'RW', 'iso3' => 'RWA', 'flag' => '🇷🇼', 'currency_code' => 'RWF', 'currency_name' => 'Rwandan Franc', 'currency_symbol' => 'R₣', 'phone_code' => '+250'],
            ['name' => 'Saint Barthelemy', 'code' => 'BL', 'iso3' => 'BLM', 'flag' => '🇧🇱', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+590'],
            ['name' => 'Saint Helena', 'code' => 'SH', 'iso3' => 'SHN', 'flag' => '🇸🇭', 'currency_code' => 'SHP', 'currency_name' => 'Saint Helena Pound', 'currency_symbol' => '£', 'phone_code' => '+290'],
            ['name' => 'Saint Kitts And Nevis', 'code' => 'KN', 'iso3' => 'KNA', 'flag' => '🇰🇳', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1869'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'iso3' => 'LCA', 'flag' => '🇱🇨', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1758'],
            ['name' => 'Saint Martin', 'code' => 'MF', 'iso3' => 'MAF', 'flag' => '🇲🇫', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+590'],
            ['name' => 'Saint Pierre And Miquelon', 'code' => 'PM', 'iso3' => 'SPM', 'flag' => '🇵🇲', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+508'],
            ['name' => 'Saint Vincent And Grenadines', 'code' => 'VC', 'iso3' => 'VCT', 'flag' => '🇻🇨', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$', 'phone_code' => '+1784'],
            ['name' => 'Samoa', 'code' => 'WS', 'iso3' => 'WSM', 'flag' => '🇼🇸', 'currency_code' => 'WST', 'currency_name' => 'Samoan Tala', 'currency_symbol' => 'WS$', 'phone_code' => '+684'],
            ['name' => 'San Marino', 'code' => 'SM', 'iso3' => 'SMR', 'flag' => '🇸🇲', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+378'],
            ['name' => 'Sao Tome And Principe', 'code' => 'ST', 'iso3' => 'STP', 'flag' => '🇸🇹', 'currency_code' => 'STD', 'currency_name' => 'São Tomé and Príncipe Dobra', 'currency_symbol' => 'Db', 'phone_code' => '+239'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'iso3' => 'SAU', 'flag' => '🇸🇦', 'currency_code' => 'SAR', 'currency_name' => 'Saudi Riyal', 'currency_symbol' => '﷼', 'phone_code' => '+966'],
            ['name' => 'Senegal', 'code' => 'SN', 'iso3' => 'SEN', 'flag' => '🇸🇳', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+221'],
            ['name' => 'Serbia', 'code' => 'RS', 'iso3' => 'SRB', 'flag' => '🇷🇸', 'currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar', 'currency_symbol' => 'Дин.', 'phone_code' => '+381'],
            ['name' => 'Seychelles', 'code' => 'SC', 'iso3' => 'SYC', 'flag' => '🇸🇨', 'currency_code' => 'SCR', 'currency_name' => 'Seychellois Rupee', 'currency_symbol' => '₨', 'phone_code' => '+248'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'iso3' => 'SLE', 'flag' => '🇸🇱', 'currency_code' => 'SLL', 'currency_name' => 'Sierra Leonean Leone', 'currency_symbol' => 'Le', 'phone_code' => '+232'],
            ['name' => 'Singapore', 'code' => 'SG', 'iso3' => 'SGP', 'flag' => '🇸🇬', 'currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar', 'currency_symbol' => '$', 'phone_code' => '+65'],
            ['name' => 'Slovakia', 'code' => 'SK', 'iso3' => 'SVK', 'flag' => '🇸🇰', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+421'],
            ['name' => 'Slovenia', 'code' => 'SI', 'iso3' => 'SVN', 'flag' => '🇸🇮', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+386'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'iso3' => 'SLB', 'flag' => '🇸🇧', 'currency_code' => 'SBD', 'currency_name' => 'Solomon Islands Dollar', 'currency_symbol' => '$', 'phone_code' => '+677'],
            ['name' => 'Somalia', 'code' => 'SO', 'iso3' => 'SOM', 'flag' => '🇸🇴', 'currency_code' => 'SOS', 'currency_name' => 'Somali Shilling', 'currency_symbol' => 'S', 'phone_code' => '+252'],
            ['name' => 'South Africa', 'code' => 'ZA', 'iso3' => 'ZAF', 'flag' => '🇿🇦', 'currency_code' => 'ZAR', 'currency_name' => 'South African Rand', 'currency_symbol' => 'R', 'phone_code' => '+27'],
            ['name' => 'South Georgia And Sandwich Isl.', 'code' => 'GS', 'iso3' => 'SGS', 'flag' => '🇬🇸', 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'currency_symbol' => '£', 'phone_code' => '+500'],
            ['name' => 'Spain', 'code' => 'ES', 'iso3' => 'ESP', 'flag' => '🇪🇸', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_code' => '+34'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'iso3' => 'LKA', 'flag' => '🇱🇰', 'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan Rupee', 'currency_symbol' => '₨', 'phone_code' => '+94'],
            ['name' => 'Sudan', 'code' => 'SD', 'iso3' => 'SDN', 'flag' => '🇸🇩', 'currency_code' => 'SDG', 'currency_name' => 'Sudanese Pound', 'currency_symbol' => 'ج.س.', 'phone_code' => '+249'],
            ['name' => 'Suriname', 'code' => 'SR', 'iso3' => 'SUR', 'flag' => '🇸🇷', 'currency_code' => 'SRD', 'currency_name' => 'Surinamese Dollar', 'currency_symbol' => '$', 'phone_code' => '+597'],
            ['name' => 'Svalbard And Jan Mayen', 'code' => 'SJ', 'iso3' => 'SJM', 'flag' => '🇸🇯', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'currency_symbol' => 'kr', 'phone_code' => '+47'],
            ['name' => 'Swaziland', 'code' => 'SZ', 'iso3' => 'SWZ', 'flag' => '🇸🇿', 'currency_code' => 'SZL', 'currency_name' => 'Swazi Lilangeni', 'currency_symbol' => 'E', 'phone_code' => '+268'],
            ['name' => 'Sweden', 'code' => 'SE', 'iso3' => 'SWE', 'flag' => '🇸🇪', 'currency_code' => 'SEK', 'currency_name' => 'Swedish Krona', 'currency_symbol' => 'kr', 'phone_code' => '+46'],
            ['name' => 'Switzerland', 'code' => 'CH', 'iso3' => 'CHE', 'flag' => '🇨🇭', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'currency_symbol' => 'Fr', 'phone_code' => '+41'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'iso3' => 'SYR', 'flag' => '🇸🇾', 'currency_code' => 'SYP', 'currency_name' => 'Syrian Pound', 'currency_symbol' => '£', 'phone_code' => '+963'],
            ['name' => 'Taiwan', 'code' => 'TW', 'iso3' => 'TWN', 'flag' => '🇹🇼', 'currency_code' => 'TWD', 'currency_name' => 'New Taiwan Dollar', 'currency_symbol' => 'NT$', 'phone_code' => '+886'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'iso3' => 'TJK', 'flag' => '🇹🇯', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani Somoni', 'currency_symbol' => 'SM', 'phone_code' => '+992'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'iso3' => 'TZA', 'flag' => '🇹🇿', 'currency_code' => 'TZS', 'currency_name' => 'Tanzanian Shilling', 'currency_symbol' => 'TSh', 'phone_code' => '+255'],
            ['name' => 'Thailand', 'code' => 'TH', 'iso3' => 'THA', 'flag' => '🇹🇭', 'currency_code' => 'THB', 'currency_name' => 'Thai Baht', 'currency_symbol' => '฿', 'phone_code' => '+66'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'iso3' => 'TLS', 'flag' => '🇹🇱', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+670'],
            ['name' => 'Togo', 'code' => 'TG', 'iso3' => 'TGO', 'flag' => '🇹🇬', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_symbol' => 'CFA', 'phone_code' => '+228'],
            ['name' => 'Tokelau', 'code' => 'TK', 'iso3' => 'TKL', 'flag' => '🇹🇰', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$', 'phone_code' => '+690'],
            ['name' => 'Tonga', 'code' => 'TO', 'iso3' => 'TON', 'flag' => '🇹🇴', 'currency_code' => 'TOP', 'currency_name' => 'Tongan Paʻanga', 'currency_symbol' => 'T$', 'phone_code' => '+676'],
            ['name' => 'Trinidad And Tobago', 'code' => 'TT', 'iso3' => 'TTO', 'flag' => '🇹🇹', 'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar', 'currency_symbol' => 'TT$', 'phone_code' => '+1868'],
            ['name' => 'Tunisia', 'code' => 'TN', 'iso3' => 'TUN', 'flag' => '🇹🇳', 'currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar', 'currency_symbol' => 'د.ت', 'phone_code' => '+216'],
            ['name' => 'Turkey', 'code' => 'TR', 'iso3' => 'TUR', 'flag' => '🇹🇷', 'currency_code' => 'TRY', 'currency_name' => 'Turkish Lira', 'currency_symbol' => '₺', 'phone_code' => '+90'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'iso3' => 'TKM', 'flag' => '🇹🇲', 'currency_code' => 'TMT', 'currency_name' => 'Turkmenistani Manat', 'currency_symbol' => 'T', 'phone_code' => '+993'],
            ['name' => 'Turks And Caicos Islands', 'code' => 'TC', 'iso3' => 'TCA', 'flag' => '🇹🇨', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1649'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'iso3' => 'TUV', 'flag' => '🇹🇻', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_code' => '+688'],
            ['name' => 'Uganda', 'code' => 'UG', 'iso3' => 'UGA', 'flag' => '🇺🇬', 'currency_code' => 'UGX', 'currency_name' => 'Ugandan Shilling', 'currency_symbol' => 'USh', 'phone_code' => '+256'],
            ['name' => 'Ukraine', 'code' => 'UA', 'iso3' => 'UKR', 'flag' => '🇺🇦', 'currency_code' => 'UAH', 'currency_name' => 'Ukrainian Hryvnia', 'currency_symbol' => '₴', 'phone_code' => '+380'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'iso3' => 'ARE', 'flag' => '🇦🇪', 'currency_code' => 'AED', 'currency_name' => 'UAE Dirham', 'currency_symbol' => 'د.إ', 'phone_code' => '+971'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'iso3' => 'GBR', 'flag' => '🇬🇧', 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'currency_symbol' => '£', 'phone_code' => '+44'],
            ['name' => 'United States', 'code' => 'US', 'iso3' => 'USA', 'flag' => '🇺🇸', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1'],
            ['name' => 'United States Outlying Islands', 'code' => 'UM', 'iso3' => 'UMI', 'flag' => '🇺🇲', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1'],
            ['name' => 'Uruguay', 'code' => 'UY', 'iso3' => 'URY', 'flag' => '🇺🇾', 'currency_code' => 'UYU', 'currency_name' => 'Uruguayan Peso', 'currency_symbol' => '$U', 'phone_code' => '+598'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'iso3' => 'UZB', 'flag' => '🇺🇿', 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistan Som', 'currency_symbol' => 'лв', 'phone_code' => '+998'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'iso3' => 'VUT', 'flag' => '🇻🇺', 'currency_code' => 'VUV', 'currency_name' => 'Vanuatu Vatu', 'currency_symbol' => 'VT', 'phone_code' => '+678'],
            ['name' => 'Venezuela', 'code' => 'VE', 'iso3' => 'VEN', 'flag' => '🇻🇪', 'currency_code' => 'VEF', 'currency_name' => 'Venezuelan Bolívar', 'currency_symbol' => 'Bs', 'phone_code' => '+58'],
            ['name' => 'Viet Nam', 'code' => 'VN', 'iso3' => 'VNM', 'flag' => '🇻🇳', 'currency_code' => 'VND', 'currency_name' => 'Vietnamese Dong', 'currency_symbol' => '₫', 'phone_code' => '+84'],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'iso3' => 'VGB', 'flag' => '🇻🇬', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1284'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'iso3' => 'VIR', 'flag' => '🇻🇮', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'phone_code' => '+1340'],
            ['name' => 'Wallis And Futuna', 'code' => 'WF', 'iso3' => 'WLF', 'flag' => '🇼🇫', 'currency_code' => 'XPF', 'currency_name' => 'CFP Franc', 'currency_symbol' => '₣', 'phone_code' => '+681'],
            ['name' => 'Western Sahara', 'code' => 'EH', 'iso3' => 'ESH', 'flag' => '🇪🇭', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham', 'currency_symbol' => 'DH', 'phone_code' => '+212'],
            ['name' => 'Yemen', 'code' => 'YE', 'iso3' => 'YEM', 'flag' => '🇾🇪', 'currency_code' => 'YER', 'currency_name' => 'Yemeni Rial', 'currency_symbol' => '﷼', 'phone_code' => '+967'],
            ['name' => 'Zambia', 'code' => 'ZM', 'iso3' => 'ZMB', 'flag' => '🇿🇲', 'currency_code' => 'ZMW', 'currency_name' => 'Zambian Kwacha', 'currency_symbol' => 'ZK', 'phone_code' => '+260'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'iso3' => 'ZWE', 'flag' => '🇿🇼', 'currency_code' => 'ZWL', 'currency_name' => 'Zimbabwean Dollar', 'currency_symbol' => '$', 'phone_code' => '+263'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['code' => $country['code']],
                array_merge($country, [
                    'status' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
